[[redirects]]
    from = "/news"
    to = "https://newsapi.org/v2/top-headlines?q=cryptocurrency&from=2022-10-14&sortBy=popularity&apiKey=79c312aee7bd45849389593d83d5e00a"
    status = 200
    force = true
    headers = {79c312aee7bd45849389593d83d5e00a = "Netlify"}

[[redirects]]
    from = "/"
    to = "https://newsapi.org/v2/top-headlines?q=cryptocurrency&from=2022-10-14&sortBy=popularity&apiKey=79c312aee7bd45849389593d83d5e00a"
    status = 200
    force = true
    headers = {79c312aee7bd45849389593d83d5e00a = "Netlify"}
